# Import Library

In [1]:
from keras.utils import np_utils
import numpy as np
from keras.models import Sequential 
import pandas as pd
from keras.layers import Dense, Activation
from matplotlib import pyplot as plt
from sklearn.preprocessing import OneHotEncoder

Using TensorFlow backend.


# 讀取Iris.csv

In [2]:
iris = pd.read_csv('Iris.csv')
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

# 資料預處理

In [3]:
x_Train=np.array(iris.loc[:,['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm',]])
y_Train=np.array(iris['Species'])
x_Train

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y_Train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [5]:
y_TrainOneHot = np_utils.to_categorical(y_Train).astype(int)
y_TrainOneHot

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

# 建立模型

In [6]:
model = Sequential()

In [7]:
model.add(Dense(units=3, 
                input_dim=4, 
                kernel_initializer='normal', 
                activation='softmax'))

print(model.summary())



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________
None


# 訓練模型

In [8]:
model.compile(loss='categorical_crossentropy', 
              optimizer='adam', metrics=['accuracy'])

In [11]:
train_history=model.fit(x=x_Train,
                        y=y_TrainOneHot,validation_split=0.2, 
                        epochs=200, batch_size=35,verbose=2)

Train on 120 samples, validate on 30 samples
Epoch 1/200
 - 0s - loss: 0.2050 - acc: 0.9583 - val_loss: 0.6946 - val_acc: 0.5333
Epoch 2/200
 - 0s - loss: 0.2049 - acc: 0.9583 - val_loss: 0.6930 - val_acc: 0.5333
Epoch 3/200
 - 0s - loss: 0.2048 - acc: 0.9583 - val_loss: 0.6921 - val_acc: 0.5333
Epoch 4/200
 - 0s - loss: 0.2046 - acc: 0.9583 - val_loss: 0.6953 - val_acc: 0.5333
Epoch 5/200
 - 0s - loss: 0.2045 - acc: 0.9583 - val_loss: 0.6953 - val_acc: 0.5333
Epoch 6/200
 - 0s - loss: 0.2044 - acc: 0.9583 - val_loss: 0.6964 - val_acc: 0.5333
Epoch 7/200
 - 0s - loss: 0.2043 - acc: 0.9583 - val_loss: 0.6955 - val_acc: 0.5333
Epoch 8/200
 - 0s - loss: 0.2042 - acc: 0.9500 - val_loss: 0.7018 - val_acc: 0.5333
Epoch 9/200
 - 0s - loss: 0.2040 - acc: 0.9500 - val_loss: 0.7038 - val_acc: 0.5333
Epoch 10/200
 - 0s - loss: 0.2039 - acc: 0.9500 - val_loss: 0.7046 - val_acc: 0.5333
Epoch 11/200
 - 0s - loss: 0.2038 - acc: 0.9500 - val_loss: 0.7042 - val_acc: 0.5333
Epoch 12/200
 - 0s - loss: 0.

Epoch 97/200
 - 0s - loss: 0.1930 - acc: 0.9667 - val_loss: 0.6651 - val_acc: 0.6000
Epoch 98/200
 - 0s - loss: 0.1929 - acc: 0.9667 - val_loss: 0.6657 - val_acc: 0.6000
Epoch 99/200
 - 0s - loss: 0.1928 - acc: 0.9667 - val_loss: 0.6653 - val_acc: 0.6000
Epoch 100/200
 - 0s - loss: 0.1928 - acc: 0.9667 - val_loss: 0.6605 - val_acc: 0.6000
Epoch 101/200
 - 0s - loss: 0.1926 - acc: 0.9667 - val_loss: 0.6612 - val_acc: 0.6000
Epoch 102/200
 - 0s - loss: 0.1924 - acc: 0.9667 - val_loss: 0.6620 - val_acc: 0.6000
Epoch 103/200
 - 0s - loss: 0.1924 - acc: 0.9667 - val_loss: 0.6658 - val_acc: 0.5667
Epoch 104/200
 - 0s - loss: 0.1922 - acc: 0.9667 - val_loss: 0.6681 - val_acc: 0.5667
Epoch 105/200
 - 0s - loss: 0.1922 - acc: 0.9667 - val_loss: 0.6657 - val_acc: 0.6000
Epoch 106/200
 - 0s - loss: 0.1919 - acc: 0.9667 - val_loss: 0.6626 - val_acc: 0.6000
Epoch 107/200
 - 0s - loss: 0.1918 - acc: 0.9667 - val_loss: 0.6607 - val_acc: 0.6000
Epoch 108/200
 - 0s - loss: 0.1918 - acc: 0.9667 - val_lo

Epoch 193/200
 - 0s - loss: 0.1814 - acc: 0.9667 - val_loss: 0.6651 - val_acc: 0.5667
Epoch 194/200
 - 0s - loss: 0.1813 - acc: 0.9667 - val_loss: 0.6570 - val_acc: 0.6000
Epoch 195/200
 - 0s - loss: 0.1812 - acc: 0.9667 - val_loss: 0.6510 - val_acc: 0.6333
Epoch 196/200
 - 0s - loss: 0.1810 - acc: 0.9667 - val_loss: 0.6488 - val_acc: 0.6333
Epoch 197/200
 - 0s - loss: 0.1808 - acc: 0.9667 - val_loss: 0.6489 - val_acc: 0.6333
Epoch 198/200
 - 0s - loss: 0.1807 - acc: 0.9667 - val_loss: 0.6489 - val_acc: 0.6333
Epoch 199/200
 - 0s - loss: 0.1806 - acc: 0.9667 - val_loss: 0.6459 - val_acc: 0.6333
Epoch 200/200
 - 0s - loss: 0.1805 - acc: 0.9667 - val_loss: 0.6412 - val_acc: 0.6333
